from django.contrib.auth.models import User
from aid_app.models import UserProfile, MedicalKit, Responder, KitItem, Product, Incident, Order, Feedback, SystemReport, Facility, IncidentStatusHistory, ResponderAvailabilityHistory, Notification

def run_cleanup():
    print("Starting database cleanup...")
    
    # 1. Identify Superusers (to keep)
    superusers = User.objects.filter(is_superuser=True)
    print(f"Preserving {superusers.count()} superusers: {[u.username for u in superusers]}")
    
    # 2. Delete non-superusers
    # This cascades to UserProfile, and usually to related objects like Orders, Incidents, Products (if set to CASCADE)
    non_superusers = User.objects.filter(is_superuser=False)
    user_count = non_superusers.count()
    if user_count > 0:
        non_superusers.delete()
        print(f"Deleted {user_count} non-superuser accounts and their cascading data.")
    else:
        print("No non-superuser accounts found.")

    # 3. Explicitly delete any potentially remaining data not linked to users or linked to admins but should be cleared
    # e.g. Reports generated by system or admin
    
    # Delete all Kit Items (usually cascade from MedicalKit, but safe to be explicit)
    kit_items_deleted = KitItem.objects.all().delete()
    print(f"Deleted remaining Kit Items: {kit_items_deleted[0]}")

    # Delete all Medical Kits
    kits_deleted = MedicalKit.objects.all().delete()
    print(f"Deleted remaining Medical Kits: {kits_deleted[0]}")

    # Delete all Products (just in case any are orphan or linked to superuser for testing)
    products_deleted = Product.objects.all().delete()
    print(f"Deleted remaining Products: {products_deleted[0]}")

    # Delete all Orders
    orders_deleted = Order.objects.all().delete()
    print(f"Deleted remaining Orders: {orders_deleted[0]}")
    
    # Delete all Incidents
    incidents_deleted = Incident.objects.all().delete()
    print(f"Deleted remaining Incidents: {incidents_deleted[0]}")

    # Delete all System Reports
    reports_deleted = SystemReport.objects.all().delete()
    print(f"Deleted all System Reports: {reports_deleted[0]}")
    
    # Delete all Feedbacks
    feedbacks_deleted = Feedback.objects.all().delete()
    print(f"Deleted all Feedbacks: {feedbacks_deleted[0]}")
    
    # Delete all Notifications
    notifications_deleted = Notification.objects.all().delete()
    print(f"Deleted all Notifications: {notifications_deleted[0]}")

    print("Database cleanup finished successfully.")

if __name__ == '__main__':
    # This setup allows running via 'python manage.py shell' conveniently if pasted, 
    # but since we run via file, we just call the function if this script is executed in a django context.
    # We'll run it via: python manage.py shell -c "from cleanup_db import run_cleanup; run_cleanup()"
    pass
