# Generated by Django 6.0 on 2025-12-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0005_systemreport_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
