# Generated by Django 6.0 on 2025-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0006_feedback_replied_at_feedback_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
