# Generated by Django 6.0 on 2025-12-31 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0007_userprofile_shipping_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(default='health_and_safety', help_text='Material Icon name', max_length=50)),
                ('urgency', models.CharField(choices=[('critical', 'Life-Threatening'), ('urgent', 'Urgent'), ('moderate', 'Moderate')], default='moderate', max_length=20)),
                ('steps', models.TextField(help_text='Enter each step on a new line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
