# Generated by Django 6.0 on 2026-01-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0009_incident_assigned_responder_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('providing_aid', 'Providing Aid'), ('transporting', 'Transporting'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
