# Generated by Django 6.0 on 2026-01-01 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0010_alter_incident_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='aid_app.incident'),
        ),
    ]
