# Generated by Django 6.0 on 2026-01-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0011_feedback_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponderAvailabilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('unavailable', 'Unavailable')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='aid_app.responder')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
