# Generated by Django 6.0 on 2026-01-01 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0012_responderavailabilityhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('providing_aid', 'Providing Aid'), ('transporting', 'Transporting'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='aid_app.incident')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
