# Generated by Django 6.0 on 2026-01-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0014_responder_handled_incidents_responder_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
