# Generated by Django 6.0 on 2026-01-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0016_order_carrier_order_current_location_order_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('critical', 'Critical'), ('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority'), ('info', 'Information')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('incident', 'Incident'), ('system', 'System'), ('maintenance', 'Maintenance'), ('staff', 'Staff'), ('equipment', 'Equipment')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_notifications', to='aid_app.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
