# Generated by Django 6.0 on 2026-01-17 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0017_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstaidguide',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='firstaidguide',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_guides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='firstaidguide',
            name='icon',
            field=models.CharField(default='health_and_safety', help_text='Material Icons name', max_length=50),
        ),
        migrations.AlterField(
            model_name='firstaidguide',
            name='steps',
            field=models.TextField(help_text='Enter steps separated by newlines'),
        ),
        migrations.AlterField(
            model_name='firstaidguide',
            name='urgency',
            field=models.CharField(choices=[('moderate', 'Moderate'), ('urgent', 'Urgent'), ('critical', 'Critical (Life-Threatening)')], default='moderate', max_length=20),
        ),
    ]
