# Generated by Django 6.0 on 2026-01-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_app', '0018_alter_firstaidguide_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
