from django.urls import path
from . import views

app_name = 'aid_app' # Namespace for your app's URLs

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('otp-verification/', views.otp_verification_view, name='otp_verification'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-panel/', views.admin_dashboard_view, name='admin_dashboard'),
    path('responder-dashboard/', views.responder_dashboard_view, name='responder_dashboard'),
    path('facility-dashboard/', views.facility_dashboard_view, name='facility_dashboard'),
    path('seller-dashboard/', views.seller_dashboard_view, name='seller_dashboard'),
    
    # Facility Manager URLs
    path('manage-kits/', views.manage_kits_view, name='manage_kits'),
    path('stock-tracking/', views.stock_tracking_view, name='stock_tracking'),
    path('stock-tracking/facility_notifications.html', views.facility_notifications_view, name='facility_notifications_alt'),
    path('stock-tracking/facility_reports.html', views.facility_reports_view, name='facility_reports_alt'),
    path('stock-tracking/facility_incident_log.html', views.facility_incident_log_view, name='facility_incident_log_alt'),
    path('stock-tracking/assign_responders.html', views.assign_responders_view, name='assign_responders_alt'),
    path('assign-responders/facility_notifications.html', views.facility_notifications_view, name='assign_responders_notifications_alt'),
    path('assign-responders/facility_reports.html', views.facility_reports_view, name='assign_responders_reports_alt'),
    path('assign-responders/facility_incident_log.html', views.facility_incident_log_view, name='assign_responders_incident_log_alt'),
    path('assign-responders/assign_responders.html', views.assign_responders_view, name='assign_responders_self_alt'),
    path('assign-responders/stock_tracking.html', views.stock_tracking_view, name='assign_responders_stock_tracking_alt'),
    path('assign-responders/logout.html', views.logout_view, name='assign_responders_logout_alt'),
    path('facility-reports/facility_notifications.html', views.facility_notifications_view, name='facility_reports_notifications_alt'),
    path('facility-reports/facility_incident_log.html', views.facility_incident_log_view, name='facility_reports_incident_log_alt'),
    path('facility-reports/assign_responders.html', views.assign_responders_view, name='facility_reports_assign_responders_alt'),
    path('facility-reports/stock_tracking.html', views.stock_tracking_view, name='facility_reports_stock_tracking_alt'),
    path('facility-reports/manage_kits.html', views.manage_kits_view, name='facility_reports_manage_kits_alt'),
    path('assign-responders/', views.assign_responders_view, name='assign_responders'),
    path('facility-incident-log/', views.facility_incident_log_view, name='facility_incident_log'),
    path('facility-reports/', views.facility_reports_view, name='facility_reports'),
    path('facility-notifications/', views.facility_notifications_view, name='facility_notifications'),
    path('facility-profile/', views.facility_profile_view, name='facility_profile'),
    path('facility/add-guide/', views.add_guide_view, name='add_guide'),
    
    path('seller-dashboard/sales_report.html', views.sales_report_redirect_view),
    path('seller-report/', views.seller_report_view, name='seller_report'),
    path('seller-profile/', views.seller_profile_view, name='seller_profile'),
    path('generate-seller-report/', views.generate_seller_report_view, name='generate_seller_report'),
    path('create-sample-orders/', views.create_sample_orders_view, name='create_sample_orders'),
    path('add-product/', views.add_product_view, name='add_product'),
    path('update-product/', views.update_product_view, name='update_product'),
    path('view-products/', views.view_products_view, name='view_products'),
    path('view-orders/', views.view_orders_view, name='view_orders'),
    path('manage-delivery/', views.manage_delivery_view, name='manage_delivery'),
    path('available-incidents/', views.available_incidents_view, name='available_incidents'),
    path('accept-incident/', views.accept_incident_view, name='accept_incident'),
    path('update-incident-status/', views.update_incident_status_view, name='update_incident_status'),
    path('responder-history/', views.responder_history_view, name='responder_history'),
    path('availability-status/', views.availability_status_view, name='availability_status'),
    path('responder-profile/', views.responder_profile_view, name='responder_profile'),
    path('feedback-received/', views.feedback_received_view, name='feedback_received'),
    path('user_dashboard', views.dashboard_view, name='user_dashboard_redirect'),  # Handle common typo
    
    # Placeholder URLs for dashboard navigation
    path('report-incident/', views.report_incident_view, name='report_incident'),
    path('first-aid-guides/', views.first_aid_guides_view, name='first_aid_guides'),
    path('buy-products/', views.buy_products_view, name='buy_products'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('shipping/', views.shipping_view, name='shipping'),
    path('payment/', views.payment_view, name='payment'),
    path('confirmation/', views.confirmation_view, name='confirmation'),
    path('book-responder/', views.book_responder_view, name='book_responder'),
    path('track_responder_new.html', views.track_responder_view, name='track_responder'),
    path('profile/', views.profile_view, name='profile'),
    path('order-history/', views.order_history_view, name='order_history'),
    path('processing/', views.processing_view, name='processing'),
    path('incident-history/', views.incident_history_view, name='incident_history'),
    path('give-feedback/', views.give_feedback_view, name='give_feedback'),
    path('my-feedback/', views.my_feedback_view, name='my_feedback'),
    path('reply-feedback/<int:feedback_id>/', views.reply_feedback_view, name='reply_feedback'),
    path('logout/', views.logout_view, name='logout'),
    path('about/', views.about_view, name='about'),
    path('contact/', views.contact_view, name='contact'),
    
    # New admin page URLs
    path('manage-users/', views.manage_users_view, name='manage_users'),
    path('manage-responders/', views.manage_responders_view, name='manage_responders'),
    path('manage-facilities/', views.manage_facilities_view, name='manage_facilities'),
    path('view-all-incidents/', views.view_all_incidents_view, name='view_all_incidents'),
    path('incident-reports/', views.incident_reports_view, name='incident_reports'),
    path('approve-sellers/', views.approve_sellers_view, name='approve_sellers'),
    path('marketplace-monitor/', views.marketplace_monitor_view, name='marketplace_monitor'),
    path('system-reports/', views.system_reports_view, name='system_reports'),
    path('feedback-analysis/', views.feedback_analysis_view, name='feedback_analysis'),
    
    # Order Management URLs
    path('create-order/', views.create_order_view, name='create_order'),
    path('cancel-order/<int:order_id>/', views.cancel_order_view, name='cancel_order'),
    path('admin/orders/', views.admin_orders_view, name='admin_orders'),
]