from django.urls import path
from . import views

app_name = 'aid_app' # Namespace for your app's URLs

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('otp-verification/', views.otp_verification_view, name='otp_verification'),
    path('change-password/', views.change_password_view, name='change_password'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('admin-panel/', views.admin_dashboard_view, name='admin_dashboard'),
    path('responder-dashboard/', views.responder_dashboard_view, name='responder_dashboard'),
    path('facility-dashboard/', views.facility_dashboard_view, name='facility_dashboard'),
    path('seller-dashboard/', views.seller_dashboard_view, name='seller_dashboard'),
    
    # Facility Manager URLs
    path('manage-kits/', views.manage_kits_view, name='manage_kits'),
    path('api/kit/add/', views.add_kit_api, name='add_kit_api'),
    path('api/kit/<str:kit_id>/edit/', views.edit_kit_api, name='edit_kit_api'),
    path('api/kit/<str:kit_id>/view/', views.view_kit_api, name='view_kit_api'),
    path('api/kit/check/', views.check_kit_api, name='check_kit_api'),
    path('api/stock/update/', views.update_stock_api, name='update_stock_api'),
    path('stock-tracking/', views.stock_tracking_view, name='stock_tracking'),
    path('assign-responders/', views.assign_responders_view, name='assign_responders'),
    path('api/assign/create/', views.create_assignment_api, name='create_assignment_api'),
    path('facility-incident-log/', views.facility_incident_log_view, name='facility_incident_log'),
    path('facility-reports/', views.facility_reports_view, name='facility_reports'),
    path('facility-notifications/', views.facility_notifications_view, name='facility_notifications'),
    path('manage-guides/', views.facility_dashboard_view, name='manage_guides'),
    path('add-guide/', views.add_guide_view, name='add_guide'),
    path('facility-profile/', views.facility_profile_view, name='facility_profile'),
    path('facility-profile/delete/', views.delete_facility_account, name='delete_facility_account'),
    path('api/notifications/mark-read/<int:notification_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('api/notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    
    path('seller-dashboard/sales_report.html', views.sales_report_redirect_view),
    path('seller-report/', views.seller_report_view, name='seller_report'),
    path('seller-profile/', views.seller_profile_view, name='seller_profile'),
    path('seller-profile/delete/', views.delete_seller_account, name='delete_seller_account'),
    path('generate-seller-report/', views.generate_seller_report_view, name='generate_seller_report'),
    path('create-sample-orders/', views.create_sample_orders_view, name='create_sample_orders'),
    path('add-product/', views.add_product_view, name='add_product'),
    path('update-product/', views.update_product_view, name='update_product'),
    path('update-product/<int:product_id>/', views.update_product_view, name='update_product_with_id'),
    path('view-products/', views.view_products_view, name='view_products'),
    path('view-orders/', views.view_orders_view, name='view_orders'),
    path('manage-delivery/', views.manage_delivery_view, name='manage_delivery'),
    path('schedule-pickup/', views.schedule_pickup_view, name='schedule_pickup'),
    path('bulk-ship/', views.bulk_ship_view, name='bulk_ship'),
    path('update-delivery-location/', views.update_delivery_location, name='update_delivery_location'),
    path('api/delivery-data/', views.get_delivery_data, name='get_delivery_data'),
    path('available-incidents/', views.available_incidents_view, name='available_incidents'),
    path('accept-incident/', views.accept_incident_view, name='accept_incident'),
    path('update-incident-status/', views.update_incident_status_view, name='update_incident_status'),
    path('api/trigger-medical-alert/', views.trigger_medical_alert, name='trigger_medical_alert'),
    path('api/forward-medical-alert/', views.forward_medical_alert, name='forward_medical_alert'),
    path('responder-history/', views.responder_history_view, name='responder_history'),
    path('availability-status/', views.availability_status_view, name='availability_status'),
    path('toggle-responder-status/', views.toggle_responder_status, name='toggle_responder_status'),
    path('responder-profile/', views.responder_profile_view, name='responder_profile'),
    path('feedback-received/', views.feedback_received_view, name='feedback_received'),
    path('user_dashboard', views.dashboard_view, name='user_dashboard_redirect'),  # Handle common typo
    
    # Placeholder URLs for dashboard navigation
    path('report-incident/', views.report_incident_view, name='report_incident'),
    path('first-aid-guides/', views.first_aid_guides_view, name='first_aid_guides'),
    path('buy-products/', views.buy_products_view, name='buy_products'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('shipping/', views.shipping_view, name='shipping'),
    path('payment/', views.payment_view, name='payment'),
    path('process-checkout/', views.process_checkout, name='process_checkout'),
    path('confirmation/', views.confirmation_view, name='confirmation'),
    path('book-responder/', views.book_responder_view, name='book_responder'),
    path('track_responder_new.html', views.track_responder_view, name='track_responder'),
    path('profile/', views.profile_view, name='profile'),
    path('api/update-profile/', views.update_profile_api, name='update_profile_api'),
    path('delete-account/', views.delete_account_view, name='delete_account'),
    path('order-history/', views.order_history_view, name='order_history'),
    path('processing/', views.processing_view, name='processing'),
    path('order/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('order/return/<int:order_id>/', views.return_order, name='return_order'),
    path('order/update-status/<int:order_id>/<str:status>/', views.update_order_status, name='update_order_status'),
    path('incident-history/', views.incident_history_view, name='incident_history'),
    path('give-feedback/', views.give_feedback_view, name='give_feedback'),
    path('my-feedback/', views.my_feedback_view, name='my_feedback'),
    path('reply-feedback/<int:feedback_id>/', views.reply_feedback_view, name='reply_feedback'),
    path('logout/', views.logout_view, name='logout'),

    path('contact/', views.contact_view, name='contact'),
    
    # New admin page URLs
    path('manage-users/', views.manage_users_view, name='manage_users'),
    path('admin-panel/bulk-actions/', views.bulk_action_users_view, name='bulk_action_users'),
    path('admin-panel/add-user/', views.add_user_view, name='add_user'),
    path('manage-responders/', views.manage_responders_view, name='manage_responders'),
    path('manage-facilities/', views.manage_facilities_view, name='manage_facilities'),
    path('view-all-incidents/', views.view_all_incidents_view, name='view_all_incidents'),
    path('admin-panel/assign-incident/<int:incident_id>/', views.assign_incident_view, name='assign_incident'),
    path('incident-reports/', views.incident_reports_view, name='incident_reports'),
    path('admin-panel/update-responder/<int:responder_id>/', views.update_responder_view, name='update_responder'),
    path('admin-panel/update-facility/<int:profile_id>/', views.update_facility_view, name='update_facility'),
    path('admin-panel/update-product-image/<int:product_id>/', views.update_product_image_view, name='update_product_image'),
    path('admin-panel/generate-report/', views.generate_report_view, name='generate_report'),
    path('approve-sellers/', views.approve_sellers_view, name='approve_sellers'),
    path('marketplace-monitor/', views.marketplace_monitor_view, name='marketplace_monitor'),
    path('system-reports/', views.system_reports_view, name='system_reports'),
    path('feedback-analysis/', views.feedback_analysis_view, name='feedback_analysis'),
    path('aid_app/api/assign/create/', views.create_assignment_api, name='create_assignment_api'),
]